### ISSUE TITLE
menu放到tableview的section0位置headerview时候，点不出下拉菜单

### ISSUE THREAD

**Issue by Rita5969** [sunnyzl/ZLDropdownMenu#3]
当把这个menu放到tableview的section0位置headerview时候，点不出下拉菜单了，请问如何修复呢，谢谢，望回复

**Comment by sunnyzl** [comment]
已修复，请重新pull一次代码

**Comment by sunnyzl** [comment]
已修复，请你重新pull一次代码，因最初做的时候下拉是添加在superView上造成的，现改为添加在keywindow上

**Comment by Rita5969** [comment]
问题解决了，谢谢您
