### ISSUE TITLE
将menu添加到tableview的headerView，点击下拉按钮，就会报错masonry的异常

### ISSUE THREAD

**Issue by houweibo** [sunnyzl/ZLDropdownMenu#7]
couldn't find a common superview for异常错误。 因为弹出的选择colletionview添加到window和menu的父类view不是同一个view。这个问题怎么解决？

**Comment by sunnyzl** [comment]
你好，能否将你的代码发给我，我这里没有复现出来这个bug

**Comment by sunnyzl** [comment]
真机上复现出来了，稍等，我看看怎么解决

**Comment by houweibo** [comment]
en，谢谢。哥们解决了吗

**Comment by sunnyzl** [comment]
已经解决，是因为坐标系的原因，请重新pull一次代码

**Comment by houweibo** [comment]
好的，谢谢
