### ISSUE TITLE
SubMenu not working in swift

### ISSUE THREAD

**Issue by kanishkatn** [sunnyzl/ZLDropdownMenu#8]
Hi,

I am using the menu in swift. The menu loads properly, but the sub menu is not showing up on click. 

Please help. 

Amazing job BTW. My boss loved it.

**Comment by sunnyzl** [comment]
I've used it in swift.But I don't find this bug. It can works in swift.

**Comment by sunnyzl** [comment]
Do you wanna the menu title  can show except the sub title?

**Comment by kanishkatn** [comment]
It seems like the delegate methods are not getting called on click of a menu item. Do I need to do any additional configurations to get it working?

**Comment by sunnyzl** [comment]
you should realize it like this

```
 func numberOfColumnsInMenu(menu: ZLDropDownMenu!) -> Int {
        return mainArray.count
    }

    func menu(menu: ZLDropDownMenu!, numberOfRowsInColumns column: Int) -> Int {
        return subArray[column].count
    }

    func menu(menu: ZLDropDownMenu!, titleForColumn column: Int) -> String! {
        return self.mainArray[column] as! String
    }

    func menu(menu: ZLDropDownMenu!, titleForRowAtIndexPath indexPath: ZLIndexPath!) -> String! {
        let array = subArray[indexPath.column] as! NSArray

        return array[indexPath.row] as! String
    }
//
    func menu(menu: ZLDropDownMenu!, didSelectRowAtIndexPath indexPath: ZLIndexPath!) {
        let array = subArray[indexPath.column] as! NSArray
        print(array[indexPath.row])
    }

```

**Comment by sunnyzl** [comment]
Can you give me your e-mail.I can send a demo for you.

**Comment by kanishkatn** [comment]
I have done that. It is calling all the other delegate methods except didSelectRowAtIndexPath. 

Please send it to kanishkatn@gmail.com

Thank you so much.

**Comment by kanishkatn** [comment]
It helped me fix the issue. Thank again :)

**Comment by sunnyzl** [comment]
You are welcome.

**Comment by HasmukhDobariya** [comment]
Also sub menu not work for me in swift. can you send me demo to dhgroup.c@gmail.com ?

**Comment by sunnyzl** [comment]
Can't show in iOS11?

**Comment by sunnyzl** [comment]
I've already sent the demo to you. If it can help you solve this problem, please close this issue

**Comment by sunnyzl** [comment]
If you use SnapKit to layout the UI, you can instead the Masonry to SnapKit
